services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha_super_segura
      - POSTGRES_DB=meu-postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432