services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - DATABASE_URL=postgresql://postgres:senha_super_segura/meu-postgres/POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432